# Generated by Django 5.0.6 on 2024-06-28 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "categorias",
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50)),
                ("apellidos", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "usuarios",
            },
        ),
        migrations.CreateModel(
            name="Grupo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50)),
                ("descripcion", models.TextField()),
                ("numero_miembros", models.IntegerField(default=0)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grupos",
                        to="core.categoria",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grupos",
                        to="core.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "grupos",
            },
        ),
        migrations.CreateModel(
            name="GrupoUsuario",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grupo_usuario",
                        to="core.grupo",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grupo_usuario",
                        to="core.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "grupo_usuario",
            },
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(max_length=50)),
                ("comentario", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="core.grupo",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="core.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "comentarios",
            },
        ),
    ]
